#%RAML 1.0 NamedExample
{
  "client_id": "0oamrfnzee1AA7kaZ0h7 ",
  "client_name": "sipApp123X",
  "redirect_uris": [
    "https://httpbin.org/get"
  ],
  "response_types": [
    "code",
    "token",
    "id_token"
  ],
  "grant_types": [
    "refresh_token",
    "authorization_code",
    "implicit"
  ],
  "token_endpoint_auth_method": "client_secret_basic",
  "application_type": "web"
}