#%RAML 1.0 NamedExample
  {
      "client_id": "<generated ID here",
      "client_secret": "generatedSecret",
      "client_id_issued_at": 1564165877,
      "client_secret_expires_at": 0,
      "client_name": "siqAppName123",
      "client_uri": null,
      "logo_uri": null,
      "redirect_uris": [
          "https://httpbin.org/get"
      ],
      "response_types": [
          "code",
          "token",
          "id_token"
      ],
      "grant_types": [
          "refresh_token",
          "authorization_code",
          "implicit",
          "client_credentials"
      ],
      "token_endpoint_auth_method": "client_secret_basic",
      "application_type": "web"
  }     