#%RAML 1.0 NamedExample
  {
    "client_name": "sidApp123",
    "redirect_uris": [
      "https://httpbin.org/get"
    ],
    "response_types": [
      "code",
      "token",
      "id_token"
    ],
    "grant_types": [
      "client_credentials"
    ],
    "token_endpoint_auth_method": "client_secret_basic",
    "application_type": "web"
  }