#%RAML 1.0 NamedExample
{
    "client_id": "0oamrf....A7kaZ0h7",
    "client_secret": "2kg.....DqT",
    "client_id_issued_at": 1565113851,
    "client_secret_expires_at": 0,
    "client_name": "sidRenamedMyApp",
    "client_uri": null,
    "logo_uri": null,
    "redirect_uris": [
        "https://httpbin.org/get"
    ],
    "response_types": [
        "code",
        "token",
        "id_token"
    ],
    "grant_types": [
        "refresh_token",
        "authorization_code",
        "implicit"
    ],
    "token_endpoint_auth_method": "client_secret_basic",
    "application_type": "web"
}