#%RAML 1.0 NamedExample
  {
      "client_id": "<same ID from URI>",
      "client_secret": "AkkildKKrv4ydaNXZMmhCV-23f-rt3z-T11bZT-EUD",
      "client_id_issued_at": 1564694594,
      "client_secret_expires_at": 0,
      "client_name": "siqAppHere",
      "client_uri": null,
      "logo_uri": null,
      "redirect_uris": [
          "http://localhost:8080/authorization-code/callback"
      ],
      "response_types": [
          "code"
      ],
      "grant_types": [
          "client_credentials",
          "authorization_code"
      ],
      "token_endpoint_auth_method": "client_secret_basic",
      "application_type": "web"
  }                
